- module-name: 'numba.core.decorators'
  anti-bloat:
    - description: 'replace decorators'
      module_code: |
        from numba.stencils.stencil import stencil

        def _wrapper(f):
            return f

        def jit(*args, **kwargs):
            return _wrapper

        def generated_jit(*args, **kwargs):
            return _wrapper

        def njit(*args, **kwargs):
            return _wrapper

        def cfunc(*args, **kwargs):
            return _wrapper

        def jit_module(*args, **kwargs):
            pass

- module-name: 'librosa.decompose'
  anti-bloat:
    - description: 'remove sklearn dependency'
      replacements_plain:
        'import sklearn.decomposition': ''

- module-name: 'librosa.segment'
  anti-bloat:
    - description: 'remove sklearn dependency'
      replacements_plain:
        'import sklearn.cluster': ''
        'import sklearn.feature_extraction': ''
        'import sklearn.neighbors': ''
        'import sklearn': ''

- module-name: 'tacotron_cleaner.cleaners'
  anti-bloat:
    - description: 'remove unidecode dependency'
      replacements_plain:
        'from unidecode import unidecode': ''
        'def convert_to_ascii(text):': ''
        'return unidecode(text)': ''

- module-name: 'soundfile'
  data-files:
    dest_path: '.'
    patterns:
      - '_soundfile_data/*'

- module-name: 'espnet'
  data-files:
    patterns:
      - 'version.txt'

- module-name: 'librosa'
  data-files:
    dirs:
      - 'util/example_data'

- module-name: 'resampy'
  data-files:
    dirs:
      - 'data'

- module-name: 'jamo'
  data-files:
    dirs:
      - 'data'